name: Test GroupMe Message

on:
  workflow_dispatch:

jobs:
  test-send:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        uses: joelwmale/webhook-action@master
        with:
          url: https://api.groupme.com/v3/bots/post
          headers: '{ "Content-Type": "application/json" }'
          body: |
            {
              "bot_id": "${{ secrets.GM_BOT_ID }}",
              "text": "keepGV active"
            }
