name: "GvAlive"

on:
  schedule:
    - cron: '30 0 */5 * *'  # 每5天的 UTC 00:30 执行一次（北京时间 08:30）
  workflow_dispatch:        # 允许手动触发

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send GroupMe Message
        run: |
          curl -X POST https://api.groupme.com/v3/bots/post \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"keepGV active\", \"bot_id\": \"${{ secrets.GM_BOT_ID }}\"}"
