name: Keep GV Alive

on:
  schedule:
    - cron: '30 1 */10 * *'  # 每10天 09:30（北京时间）运行
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send GroupMe message
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"keepGV active\", \"bot_id\": \"${{ secrets.GM_BOT_ID }}\"}" \
          https://api.groupme.com/v3/bots/post
